global:
  scrape_interval: 5s
  evaluation_interval: 10s

scrape_configs:
- job_name: 'envoy-proxy-1'
  metrics_path: '/stats/prometheus'
  scrape_interval: 5s
  static_configs:
    - targets: ['envoy:9901']